apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskboard
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: create
  SPRING_JPA_SHOW_SQL: "true"
